### ISSUE TITLE
Cannot run snapshots since moving to Vite

### ISSUE THREAD

**Issue by Spence1115** [percy/percy-storybook#714]
Been using Percy for Storybook for a while now, working fine, but recently we've been moving from Webpack to Vite, and now it does not run.

## The problem

When running `percy storybook ./storybook-static --verbose` since moving to Vite:

```bash
[percy:core:page] Page created (2ms)
[percy:core:page] Navigate to: http://localhost:34667/iframe.html (25ms)
[percy:core:page] Page navigated (206ms)
[percy:core:page] Page closed (18ms)
[percy:core] Stopping percy... (1ms)
[percy:core:browser] Closing browser (0ms)
[percy:core:browser] Browser closed (33ms)
[percy:core] Build not created (0ms)
[percy:cli] TypeError: Cannot read properties of undefined (reading 'message')
    at withPage (file:///home/circleci/project/node_modules/@percy/storybook/dist/utils.js:108:33)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async takeStorybookSnapshots (file:///home/circleci/project/node_modules/@percy/storybook/dist/snapshots.js:187:5)
    at async Object.callback (file:///home/circleci/project/node_modules/@percy/storybook/dist/storybook.js:36:3)
    at async generatePromise (file:///home/circleci/project/node_modules/@percy/core/dist/utils.js:85:115)
    at async runCommandWithContext (file:///home/circleci/project/node_modules/@percy/cli-command/dist/command.js:132:3)
    at async percy (file:///home/circleci/project/node_modules/@percy/cli-command/dist/command.js:162:9)
    at async /home/circleci/project/node_modules/@percy/cli/bin/run.cjs:13:5 
```

If I do a dry run
`percy storybook ./storybook-static --verbose --dry-run`
Everything works as expected

```bash
[percy:core] Snapshot found: Example/Inputs/SingleText: Suffix (0ms)
[percy:core:page] Page closed (2ms)
[percy:core] Found 5 snapshots (0ms)
[percy:core:browser] Closing browser (0ms)
[percy:core:browser] Browser closed (29ms)
[percy:core] Build not created (1ms)
```

## Environment

- Node version: 16.13.1
- `@percy/cli` version: 1.20.0
- OS version: Linux, running on CircleCI on the `cimg/node:16.13.1-browsers` image
- Type of shell command-line [interface]: bash

## Debug logs

Running with `--debug` gets me the same error as above

**Comment by itsjwala** [comment]
@Spence1115 could you provide a repro sample for us to debug? also, which version of Percy storybook SDK are you using?

**Comment by stephiescastle** [comment]
I had the exact same issue, and setting `storyStoreV7` to `false` has fixed it. We're using that as a workaround, as it's not ideal.

**Comment by itsjwala** [comment]
could be related to #715, closing this one in favor of that, please reopen if that's not the case.
