### ISSUE TITLE
Stories not found on window within 10 seconds.

### ISSUE THREAD

**Issue by jamesarosen** [percy/percy-storybook#92]
I've followed https://docs.percy.io/docs/storybook-tutorial as best I can, adapting it to my existing project.

My dev dependencies:
```
"devDependencies": {
  "@babel/core": "^7.0.0",
  "@babel/plugin-proposal-object-rest-spread": "^7.0.0",
  "@babel/plugin-transform-runtime": "^7.3.4",
  "@babel/preset-env": "^7.0.0",
  "@babel/preset-react": "^7.0.0",
  "@percy-io/percy-storybook": "^2.1.0",
  "@storybook/addon-actions": "^5.0.10",
  "@storybook/addon-knobs": "^5.0.10",
  "@storybook/addon-links": "^5.0.10",
  "@storybook/addons": "^5.0.10",
  "@storybook/react": "^5.0.10",
  "babel-eslint": "^10.0.1",
  "babel-jest": "^24.1.0",
  "babel-loader": "^8.0.5",
  "debug": "^4.1.1",
  "enzyme": "^3.9.0",
  "enzyme-adapter-react-16": "^1.11.2",
  "eslint": "^5.14.1",
  "eslint-config-airbnb": "^17.1.0",
  "eslint-config-prettier": "^4.1.0",
  "eslint-import-resolver-workspaces": "^1.0.6",
  "eslint-plugin-import": "^2.16.0",
  "eslint-plugin-jsx-a11y": "^6.2.1",
  "eslint-plugin-prettier": "^3.0.1",
  "eslint-plugin-react": "^7.12.4",
  "eslint-plugin-react-hooks": "^1.6.0",
  "husky": "^1.0.0-rc.7",
  "jest": "^24.1.0",
  "jest-haste-map": "^24.5.0",
  "jest-puppeteer": "^4.1.0",
  "jest-resolve": "^24.5.0",
  "mockdate": "^2.0.2",
  "node-sass": "^4.11.0",
  "prettier": "^1.12.1",
  "puppeteer": "^1.13.0",
  "react": "^16.8.6",
  "react-dom": "^16.8.6",
  "sass-loader": "^7.1.0"
},
```

I exported my percy token: `export PERCY_TOKEN=…`.

`yarn run build-storybook` is successful. And after it runs I can open `./storybook-static/index.html` in the browser and see my stories.

When I run `yarn run snapshot` I get a successful build followed by
```
info => Output directory: /Users/me/code/my-project/storybook-static
Error:  Error: Evaluation failed: Error: Stories not found on window within 10 seconds. Check your call to serializeStories in your Storybook's config.js.
    at checkStories (__puppeteer_evaluation_script__:17:16)
    at __puppeteer_evaluation_script__:14:11
    at ExecutionContext.evaluateHandle (/Users/me/code/my-project/node_modules/@percy-io/percy-storybook/node_modules/puppeteer/lib/ExecutionContext.js:80:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/Users/me/code/my-project/node_modules/@percy-io/percy-storybook/node_modules/puppeteer/lib/helper.js:110:27)
    at ExecutionContext.evaluate (/Users/me/code/my-project/node_modules/@percy-io/percy-storybook/node_modules/puppeteer/lib/ExecutionContext.js:48:31)
    at ExecutionContext.<anonymous> (/Users/me/code/my-project/node_modules/@percy-io/percy-storybook/node_modules/puppeteer/lib/helper.js:111:23)
    at DOMWorld.evaluate (/Users/me/code/my-project/node_modules/@percy-io/percy-storybook/node_modules/puppeteer/lib/DOMWorld.js:105:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (/Users/me/code/my-project/node_modules/@percy-io/percy-storybook/node_modules/puppeteer/lib/helper.js:110:27)
    at Page.evaluate (/Users/me/code/my-project/node_modules/@percy-io/percy-storybook/node_modules/puppeteer/lib/Page.js:809:43)
    at Page.<anonymous> (/Users/me/code/my-project/node_modules/@percy-io/percy-storybook/node_modules/puppeteer/lib/helper.js:111:23)
    at _callee$ (/Users/me/code/my-project/node_modules/@percy-io/percy-storybook/lib/getStories.js:64:25)
    at tryCatch (/Users/me/code/my-project/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/me/code/my-project/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/me/code/my-project/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/Users/me/code/my-project/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/me/code/my-project/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by timhaines** [comment]
Hi @jamesarosen,

I see "@percy-io/percy-storybook": "^2.1.0" in your dependencies.  If you're using Storybook v5, can you upgrade to @percy/storybook v3?  This is what the version that our [current Storybook docs](https://docs.percy.io/docs/storybook) apply to.

If you're not on Storybook v5 yet, and can't easily upgrade to it, then see our [older docs for how to configure @percy-io/percy-storybook v2](https://docs.percy.io/docs/storybook-for-react).

I'm going to close this, but will keep an eye on it in case what I've mentioned doesn't resolve the issue for you.  Also feel welcome to reach out over support.

**Comment by jamesarosen** [comment]
`"@percy-io/percy-storybook": "^3.0.0-beta.0"` worked perfectly. If only every bug were this easy to diagnose and fix!

**Comment by timhaines** [comment]
@jamesarosen Sorry, I should have been more explicit about the package name change.  What you want is [@percy/storybook v3.0.2](https://github.com/percy/percy-storybook/releases/tag/%40percy%2Fstorybook%403.0.2).

**Comment by jamesarosen** [comment]
[npm](https://www.npmjs.com/package/@percy-io/percy-storybook) doesn't have that version. Did you publish it?

**Comment by timhaines** [comment]
@jamesarosen It's [here](https://www.npmjs.com/package/@percy/storybook), right?

**Comment by jamesarosen** [comment]
Wow, I just glossed right over the package name 🙄. One of those days.

**Comment by timhaines** [comment]
I hear you James.  Right there with you today.  :)

**Comment by fedorinoGore** [comment]
Hi @timhaines 
I have just the same error while using "@storybook/react": "~4.0.12", and  "@percy-io/percy-storybook": "^2.1.0"
`
devDependencies": {
    "@babel/plugin-syntax-dynamic-import": "^7.7.4",
    "@percy-io/percy-storybook": "^2.1.0",
    "@storybook/addon-actions": "~4.0.12",
    "@storybook/addon-links": "~4.0.12",
    "@storybook/addons": "~4.0.12",
    "@storybook/react": "~4.0.12",
    "jest": "^23.6.0",
    "react-split-pane": "0.1.84"
  }
`
What could be the source of the problem in this case?

**Comment by Robdel12** [comment]
Hey @fedorinoGore! Have you tried [debugging locally](https://docs.percy.io/docs/storybook-for-react#debugging-locally) to see what the static storybook output is? This error means we weren't able to locate any stories within the static output
